# Generated by Django 4.1.5 on 2023-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
