# Generated by Django 4.1.5 on 2023-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0003_component_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='postalcode',
            field=models.IntegerField(null=True),
        ),
    ]
