# Generated by Django 4.1.5 on 2023-03-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0004_user_master_postalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='state_master',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='state_id')),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='city_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=50)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.state_master', verbose_name='state_id')),
            ],
        ),
    ]
