# Generated by Django 4.1.5 on 2023-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0005_state_master_city_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_img', models.ImageField(upload_to='laptop/')),
                ('lap_name', models.CharField(max_length=50)),
                ('lap_des', models.TextField()),
                ('lap_price', models.IntegerField()),
            ],
        ),
    ]
