# Generated by Django 4.1.5 on 2023-03-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0006_laptop_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='laptop_master',
        ),
    ]
