# Generated by Django 4.1.5 on 2023-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0008_laptop_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='pc_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_img', models.ImageField(upload_to='pc/')),
                ('pc_name', models.CharField(max_length=50)),
                ('pc_des', models.TextField()),
                ('pc_price', models.IntegerField()),
            ],
        ),
    ]
