# Generated by Django 4.1.5 on 2023-03-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0009_pc_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_master',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=50)),
                ('order_price', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.user_master', verbose_name='username')),
            ],
        ),
    ]
