# Generated by Django 4.1.5 on 2023-03-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0010_order_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_master',
        ),
    ]
