# Generated by Django 4.1.5 on 2023-03-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0011_delete_order_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_master',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=50)),
                ('order_price', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.user_master', verbose_name='username')),
            ],
        ),
    ]
