# Generated by Django 4.1.5 on 2023-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0012_order_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_master',
            name='paymethod',
            field=models.CharField(default='COD', max_length=50),
        ),
    ]
