# Generated by Django 4.1.5 on 2023-03-31 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0013_order_master_paymethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_master',
        ),
    ]
