# Generated by Django 4.1.5 on 2023-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0015_order_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField(max_length=16)),
                ('CardHolder', models.CharField(max_length=50)),
                ('expiresmonth', models.IntegerField(max_length=50)),
                ('expiresyear', models.IntegerField(max_length=50)),
                ('balance', models.IntegerField(max_length=50)),
            ],
        ),
    ]
