# Generated by Django 4.1.5 on 2023-03-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0018_card_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card_payment',
        ),
    ]
