# Generated by Django 4.1.5 on 2023-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0019_delete_card_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField()),
                ('CardHolder', models.CharField(max_length=16)),
                ('expiresmonth', models.IntegerField()),
                ('expiresyear', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
    ]
