# Generated by Django 4.1.5 on 2023-04-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0020_card_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_master',
        ),
    ]
