# Generated by Django 4.1.5 on 2023-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0022_order_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactfrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('message', models.TextField()),
            ],
        ),
    ]
