# Generated by Django 4.1.5 on 2023-04-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0023_contactfrom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactfrom',
        ),
    ]
