# Generated by Django 4.1.5 on 2023-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0025_contactfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfrom',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
