# Generated by Django 4.1.5 on 2023-04-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0028_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_master',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='state',
        ),
    ]
