# Generated by Django 4.1.5 on 2023-04-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0029_remove_order_master_state_remove_user_master_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='laptop_master',
        ),
        migrations.DeleteModel(
            name='pc_master',
        ),
    ]
