# Generated by Django 4.1.5 on 2023-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0031_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AlterField(
            model_name='games',
            name='gameimg',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='games',
            name='gamename',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
