# Generated by Django 4.1.5 on 2023-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0032_remove_games_id_alter_games_gameimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='gamename',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='gamename'),
        ),
    ]
