# Generated by Django 4.1.5 on 2023-04-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0033_alter_games_gamename'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamespc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.games', verbose_name='gamename')),
                ('pcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.component_master')),
            ],
        ),
    ]
