# Generated by Django 4.1.5 on 2023-04-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0034_gamespc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gamespc',
        ),
    ]
