# Generated by Django 4.1.5 on 2023-04-08 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0036_component_master_exp_date_component_master_mp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_master',
            name='con_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.category_master', verbose_name='con_id'),
        ),
        migrations.AlterField(
            model_name='component_master',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 18, 56, 30, 795702)),
        ),
    ]
