# Generated by Django 4.1.5 on 2023-04-08 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0037_alter_component_master_con_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_master',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 19, 55, 7, 229981)),
        ),
        migrations.CreateModel(
            name='gamespc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cabinets', models.CharField(max_length=50)),
                ('Motherboard', models.CharField(max_length=50)),
                ('Processor', models.CharField(max_length=50)),
                ('GraphicCard', models.CharField(max_length=50)),
                ('SMPS', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=50)),
                ('SSD', models.CharField(max_length=50)),
                ('HDD', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ProcessorBrand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=50)),
                ('gamename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus_app.games', verbose_name='gamename')),
            ],
        ),
    ]
