# Generated by Django 4.1.5 on 2023-04-08 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0038_alter_component_master_exp_date_gamespc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_master',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 19, 59, 9, 711068)),
        ),
    ]
