# Generated by Django 4.1.5 on 2023-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0039_alter_component_master_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_master',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
