# Generated by Django 4.1.5 on 2023-04-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_app', '0040_alter_component_master_exp_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
